### ISSUE TITLE
Use default mbed_app.json

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-os-example-nvstore#1]
The markdown documentation states that a user has to copy a json file very early in the process. However, the default file should be already in place to simplify/remove the extra step and enhance UX:

>   2. Start with the default NVStore configuration.
>
>   Copy mbed_app-default-areas.json to mbed_app.json. This should use the last two sectors (4KB each) as NVStore areas.

FYI @davidsaada

**Comment by davidsaada** [comment]
Thanks. Fixed in [this commit](https://github.com/ARMmbed/mbed-os-example-nvstore/tree/e5f13590f417c38c499767d9a9185d0078ec17b7).
