### ISSUE TITLE
main.cpp contains too much information for application developers

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-os-example-nvstore#2]
main.cpp seems to have been created to test NVSTORE with many combinations and report information on multiple errors. 

This seems great at first look. However, this example is targeted to application developers that need to see just an example.
I'd suggest simplifying the application and:
- Point on documentation for detail information
- Rely on automated tests to fully cover multiple use cases

FYI @davidsaada @adbridge

**Comment by davidsaada** [comment]
@MarceloSalazar Thanks. I guess you refer to the ```display_return_code``` function, right? I can remove it and display the return code only. Other than that, the application demonstrates the usage of NVStore APIs. Do you see any other places in in this file where your comment is relevant?

**Comment by MarceloSalazar** [comment]
To be more precise, I'd suggest:
- remove `display_return_code`, and use `strerror`
For example:
https://github.com/ARMmbed/mbed-os-example-filesystem/blob/master/main.cpp#L18

- remove `NVSTORE_ENABLED` ifdef. You can just detect that NVSTORE was not enabled and exit.

Thanks!

**Comment by davidsaada** [comment]
> remove ```NVSTORE_ENABLED``` ifdef. You can just detect that NVSTORE was not enabled and exit.

That won't work. The code won't compile that way, as non of the APIs are accessible when not enabled, hence the ifdef.
But I agree that this is a bit exaggerated. I can just remove that whole disabled scenario, including the json file and the explanation in the md file. Guess that engineers can understand what happens when a feature is disabled.

**Comment by davidsaada** [comment]
Did just that - Removed configuration for disabled scenario and eliminated the return code display function. I just print the integer return code. `strerror` won't do here, as it's used for system errors, which is not the case here.

**Comment by MarceloSalazar** [comment]
Thanks! We may need to think what message should be displayed if someone attempts to build/run on another platform.
For now, I consider this done. Thanks!

**Comment by davidsaada** [comment]
It should work pretty much the same way (unless Flash is not supported for that platform, and then it won't compile).
