### ISSUE TITLE
Failed to build with online IDE

### ISSUE THREAD

**Issue by artokin** [ARMmbed/mbed-os-example-nvstore#5]
Following error prevents online IDE compilation:
`Error: Cannot open source input file "nvstore.h": No such file or directory in "main.cpp", Line: 18, Col: 22`

**Comment by davidsaada** [comment]
As far as I managed to understand (thanks @geky for the explanation), the entire NVStore feature, including nvstore.h, aren't seen by the online IDE until the feature is in the release, hence the failure.

**Comment by geky** [comment]
You can work around this by forking mbed-os, and then importing that fork into the online compiler. Or importing https://github.com/armmbed/mbed (not mbed-os). But this is a bit of a hack.

Unless @adbridge knows a better way?

**Comment by davidsaada** [comment]
@adbridge who needs to handle this issue?

**Comment by adbridge** [comment]
This was retested in oob2 and passed, can this be closed now ?

**Comment by 0xc0170** [comment]
@davidsaada Seems I can't close this one. Feel free to close, as not relevant anymore
