### ISSUE TITLE
Failed to export from online IDE

### ISSUE THREAD

**Issue by artokin** [ARMmbed/mbed-os-example-nvstore#6]
Export from online IDE is failing with message:
`An error occured during export. Please contact support`

Exporting mbed-os-example-blinky seems to work fine.

**Comment by adbridge** [comment]
@artokin Which board/compiler ? Need to check mbed export -S to see if actually a supported combination. Does it export when using the command line ?

**Comment by davidsaada** [comment]
As far as I managed to understand (thanks @geky for the explanation), the entire NVStore feature isn't seen by the online IDE until the feature is in the release, hence the failure.

**Comment by geky** [comment]
Related https://github.com/ARMmbed/mbed-os-example-nvstore/issues/5

**Comment by adbridge** [comment]
If the partnerbeta version of the online compiler is being used as per the OOB instructions then the feature should be visible...

**Comment by theotherjimmy** [comment]
Probably related to https://github.com/ARMmbed/mbed-os/pull/6428

**Comment by cmonr** [comment]
That PR is now in. Someone mind taking another look?

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-589

**Comment by 0xc0170** [comment]
Can't reproduce anymore

@yossi2le tested for ARM GNU eclipse, eclipse GCC_ARM and eclipse IAR for the following boards K82F, K64F and ARC_PRO all pass successfully.
