### ISSUE TITLE
What data is nvstore supposed to be used to store?

### ISSUE THREAD

**Issue by ghost** [ARMmbed/mbed-os-example-nvstore#8]
This might be a silly question, but there's no indication in the README.

**Comment by davidsaada** [comment]
Fair enough. NVStore is an infrastructural module, which can be used to store any item on the flash. However, it is mainly intended for the storage of security related items, like crypto keys. I'll try to add a few words there to clarify.

**Comment by ghost** [comment]
so what is recommended to store configuration type stuff on nrf52 devices?

**Comment by davidsaada** [comment]
This feature will be used as an infrastructure for other features. For instance, we develop a feature called Device Key, which holds a per device unique seed for random generation (for devices that don't have true random generators). Later on, we will develop a secure storage, which will store the file signatures there.

**Comment by ghost** [comment]
so do you have a recommendation for configuration storage for all mbed devices (especially nrf52 devices). I really dig the interface of this vs wrangling with FlashIAP.

**Comment by davidsaada** [comment]
NVStore can be good for this purpose if you want to use a relatively small number of different keys (lets say 50), whose data size is also small (lets say <100), which don't get updated too often. Reason is that larger numbers would result in a lot of garbage collection, leading to sector erases (an operation that takes long time). On the good side, NVStore is probably the only mechanism that can work on just about any board, as all boards have internal Flash. All other boards have different storage mechanisms (SD card, external SPIF flash etc.), meaning that you will have hard time to find a uniform mechanism working for all of them. I'm not really familiar with the nrf52 devices. Will try looking at them when I'm back at work after the weekend.

**Comment by ghost** [comment]
most folks doing stuff with nrf52 end up using the SDK's fstorage library as far as i can tell, since there really wasn't an alternative. That's what the mbed Eddystone implementation  uses as well. It's not exactly a friendly API though.

The other mbed native way is setting up your own via FlashIAP, but that assumes you want to know a lot about the underlying storage topology. I was just hoping to find a method that all folks who use mbed and the BLE APIs could use to to store configuration data.

**Comment by davidsaada** [comment]
Does fstorage use the internal flash? If it does, then all issues I raised apply there as well. In this case, NVStore should definitely be a good replacement. Not to mention the FlashIAP driver (on top of which NVStore is implemented), which isn't supposed to be used for this purpose.
NVStore has one drawback though - its key management. While there are currently no features using NVStore yet, release 5.9 should introduce a few, each of which using its own NVStore key or key range. NVStore should have a way of reserving keys according to feature by then, but it is not implemented yet.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-588
